services:

  pihole:
    # docs: https://docs.pi-hole.net/docker/
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port
      - "443:443/tcp"
    environment:
      # Set the appropiate timezone
      TZ: 'America/Monterrey'
      # If using Docker's default 'bridge' network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      # For persisting Pihole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
